# ============================================================================

# CAPE Escalation Analysis System Setup Script (File Generator)
# ============================================================================

# This script creates the required directories and writes code files to the appropriate locations.

setup_directories <- function() {
  dirs <- c(
    "R",
    "inst/shiny",
    "inst/shiny/modules",
    "inst/shiny/www",
    "inst/outlay_profiles",
    "data",
    "tests/testthat",
    "docs",
    "examples",
    "deploy/shinyapps.io",
    "deploy/docker",
    "deploy/huggingface"
  )
  for (dir in dirs) {
    if (!dir.exists(dir)) dir.create(dir, recursive = TRUE)
  }
}

# Write R functions to R/
write_r_functions <- function() {
  r_code <- "#' Check R version\ncheck_r_version <- function() {\n  r_version <- as.numeric(paste0(R.version$major, '.', R.version$minor))\n  if (r_version < 4.3) {\n    stop('R version 4.3.0 or higher required. Current version: ', r_version)\n  }\n}\n\n#' Install required packages\ninstall_packages <- function() {\n  cran_packages <- c(\n    'shiny', 'shinydashboard', 'shinyWidgets',\n    'tidyverse', 'lubridate', 'zoo',\n    'fredr', 'httr', 'jsonlite',\n    'forecast', 'tseries', 'prophet',\n    'randomForest', 'xgboost', 'caret',\n    'plotly', 'DT', 'corrplot', 'viridis',\n    'openxlsx', 'knitr', 'rmarkdown',\n    'devtools', 'testthat', 'roxygen2', 'renv'\n  )\n  new_packages <- cran_packages[!(cran_packages %in% installed.packages()[,'Package'])]\n  if(length(new_packages) > 0) install.packages(new_packages, repos = 'https://cloud.r-project.org/')\n}\n"
  writeLines(r_code, "R/setup_functions.R")
}

# Write Shiny launcher to inst/shiny/
write_shiny_launcher <- function() {
  shiny_code <- "#' Launch CAPE Escalation Analysis Application\n#' @export\nlaunch_cape_app <- function(port = 3838, host = '127.0.0.1', launch.browser = TRUE) {\n  required_packages <- c('shiny', 'shinydashboard', 'tidyverse', 'fredr')\n  missing_packages <- required_packages[!required_packages %in% installed.packages()[,'Package']]\n  if(length(missing_packages) > 0) stop('Missing required packages: ', paste(missing_packages, collapse = ', '))\n  app_dir <- system.file('shiny', package = 'capeEscalation')\n  if(app_dir == '') app_dir <- 'inst/shiny'\n  shiny::runApp(appDir = app_dir, port = port, host = host, launch.browser = launch.browser)\n}\n"
  writeLines(shiny_code, "inst/shiny/launch.R")
}

# Write tests to tests/testthat/
write_tests <- function() {
  test_code <- "library(testthat)\ntest_that('R version check works', {\n  expect_no_error(check_r_version())\n})\ntest_that('Directory structure is created', {\n  expect_true(dir.exists('R'))\n  expect_true(dir.exists('inst/shiny'))\n  expect_true(dir.exists('data'))\n})\n"
  writeLines(test_code, "tests/testthat/test-setup.R")
}

# Write package files to root
write_package_files <- function() {
  description <- 'Package: capeEscalation\nType: Package\nTitle: CAPE Escalation Analysis System\nVersion: 1.0.0\nDate: 2024-01-15\nAuthors@R: person("Your", "Name", email = "your.email@example.com", role = c("aut", "cre"))\nDescription: Comprehensive system for DoD cost escalation analysis following CAPE methodology.\nLicense: MIT\nEncoding: UTF-8\nLazyData: true\nDepends: R (>= 4.3.0)\nImports: shiny, tidyverse, fredr, forecast, openxlsx\nRoxygenNote: 7.2.3\n'
  writeLines(description, "DESCRIPTION")
  namespace <- '# Generated by roxygen2: do not edit by hand\nexport(launch_cape_app)\nimportFrom(fredr,fredr_set_key)\nimportFrom(fredr,fredr_series_search_text)\nimportFrom(fredr,fredr)\nimportFrom(dplyr,"%>%")\nimportFrom(forecast,auto.arima)\nimportFrom(forecast,forecast)\n'
  writeLines(namespace, "NAMESPACE")
  buildignore <- '^.*\\.Rproj$\n^\\.Rproj\\.user$\n^README\\.md$\n^\\.github$\n^docs$\n^deploy$\n^examples$\n^\\.Renviron$\n'
  writeLines(buildignore, ".Rbuildignore")
}

# Write README
write_readme <- function() {
  readme <- '# CAPE Escalation Analysis System\n\n[![R Version](https://img.shields.io/badge/R-%3E%3D%204.3.0-blue)](https://www.r-project.org/)\n[![Shiny](https://img.shields.io/badge/Shiny-1.7.0-green)](https://shiny.rstudio.com/)\n[![License](https://img.shields.io/badge/License-MIT-yellow)](LICENSE)\n\n## Overview\n\nThe CAPE Escalation Analysis System provides DoD cost estimators with a comprehensive, CAPE-compliant tool for generating custom inflation indices.\n\n## Quick Start\n\n### Installation\n\n```r\n# Install from GitHub\ndevtools::install_github("your-org/cape-escalation")\n# Or run locally\nsource("setup.R")\nrun_setup()\n```\n\n### Launch Application\n\n```r\nlibrary(capeEscalation)\nlaunch_cape_app()\n```\n\n## Features\n- Automated PPI Index Retrieval from FRED API\n- Advanced Forecasting with time series and ML\n- Outlay Profile Integration for weighted escalation\n- CAPE Compliance validation\n- Comprehensive Export with documentation\n\n## Documentation\n- [User Guide](docs/user_guide.md)\n- [CAPE Methodology](docs/cape_methodology.md)\n- [API Reference](docs/api_reference.md)\n- [Best Practices](docs/best_practices.md)\n\n## Support\n- Issues: [GitHub Issues](https://github.com/your-org/cape-escalation/issues)\n- Email: cape-support@your-org.mil\n\n## License\nMIT License - See [LICENSE](LICENSE) file for details.\n'
  writeLines(readme, "README.md")
}

# Main function to generate files
run_file_generation <- function() {
  setup_directories()
  write_r_functions()
  write_shiny_launcher()
  write_tests()
  write_package_files()
  write_readme()
  cat("\nCAPE Escalation Analysis System file generation complete!\n")
}

# Run file generation if executed directly
if (interactive()) {
  run_file_generation()
}